### ISSUE TITLE
Using -gs option for the pdf converted from word (only text)

### ISSUE THREAD

**Issue by sant527** [abarker/pdfCropMargins#24]
I want to know will -gs (using ghostscript for bounding box) crop the same as without this option, if my document is not scanned but a word text (no images) converted to pdf.

**Comment by sant527** [comment]
I found that in some pdfs its not cropping at all with -gs

**Comment by sant527** [comment]
I am not able to crop this file using

```
pdf-crop-margins -v -gs -p4 100 0 100 100 ADI_41_43.pdf
```
[ADI_41_43_cropped.pdf](https://github.com/abarker/pdfCropMargins/files/5125711/ADI_41_43_cropped.pdf)

**Comment by abarker** [comment]
The default is to use pdftoppm to render the pages to `.ppm` files and then compute the crops from those scans.  The `-gs` option works just the same way, except that it uses Ghostscript to render the document to `.ppm` files rather than using pdftoppm.  The `--gsBbox` option does not directly render to `.ppm` files at all, but calls Ghostscript to compute the bounding boxes directly and return the results (and does not work on scanned documents).

I'm not sure why some files from the same source would work with `-gs` and some would not.  I'll look into it.

**Comment by sant527** [comment]
Thank you. Since mine is not a scanned document, i prefer to use `-gs` it requires less space in tmp and also time. Kindly have a look at the files

**Comment by abarker** [comment]
It's difficult to determine exactly what's happening, since with `-gs` Ghostscript is essentially being used as a black box to compute the bounding boxes.  I don't know the internals of its algorithm.  Ghostscript is apparently detecting some kind of PDF object near the bottoms of pages in the documents that aren't cropping correctly with `-gs`.  This object isn't affecting the rendered image versions, though.  I noticed that when I do a pre-crop of 6bp on the bottom of the document it crops as expected: `pdf-crop-margins -v -gs -p4 100 0 100 100 -ap4 0 6 0 0 ADI_41_43.pdf`.

You're also using a fairly old version of pdfCropMargins, but that doesn't seem to be causing this issue.

**Comment by sant527** [comment]
-ap option worked. (pre cropping a bit before)
