### ISSUE TITLE
Using Python - Readline

### ISSUE THREAD

**Issue by Gliks** [abarker/pdfCropMargins#26]
Hi, 

When I'm trying to run it via python I see the source asks for readline moudle. 
can you explain why? should I install it?
and how I can disable the automatic exit? 

Thanks!

**Comment by abarker** [comment]
I assume you're running from Windows.  That was a bug reported in https://github.com/abarker/pdfCropMargins/issues/25.  It should be fixed in the most recent version on PyPI, 0.2.15.  If you installed via pip, try `pip install --upgrade pdfCropMargins[gui]`.

If you still get the bug, let me know.  A copy of the error message and any output from running in verbose `-v` mode would be helpful.

**Comment by ssfjhh** [comment]
> I assume you're running from Windows. That was a bug reported in #25. It should be fixed in the most recent version on PyPI, 0.2.15. If you installed via pip, try `pip install --upgrade pdfCropMargins[gui]`.
> 
> If you still get the bug, let me know. A copy of the error message and any output from running in verbose `-v` mode would be helpful.

Hi @abarker. The bug is not fixed in the version 0.2.15.😒

**Comment by abarker** [comment]
You're right, somehow that fix didn't get pushed out to PyPI.  I put up a version 0.2.16 that should fix it; try upgrading again.  (Version 1.0.0 with faster cropping will get put up on PyPI soon, but isn't ready yet.)
