### ISSUE TITLE
Choose aspect ratio

### ISSUE THREAD

**Issue by harveyslash** [abarker/pdfCropMargins#4]
The cropping works great. But is there a way to choose the aspect ratio of a page after the files have been cropped?
I use a tablet to read some books, and cropping the margins allows the text to get bigger. But most of the time the page size is very different from the tablet screen aspect ratio (which is 4:3)

**Comment by abarker** [comment]
The program cannot change the basic text layout on a page, or the fonts used in a page.  That is fixed in the PDF.  The PDF would need to be regenerated from its source to change it.  All pdfCropMargins can do is change the cropping box around the text.  

You can change the aspect ratio of the cropped pages (but not the aspect ratio of the text on them) by using larger margins on, say, the left and right edges.  The `-p4` and `-a4` options can do that.  It would be possible to have an option to automatically set the aspect ratio by padding pages out with margins on the sides or top and bottom as needed, but that option is not currently implemented.  It would not be too difficult to implement, but I'm not sure how useful it would be since it would just add empty margin space.

**Comment by abarker** [comment]
I went ahead and implemented (and pushed to GitHub) a new option to set page ratios.  It will increase either left and right or top and bottom margins as necessary to give the resulting pages the chosen ratio of width to height.  This is done after all other crops are calculated as usual.  You can play around with it and see if it helps in your situation.

**Comment by harveyslash** [comment]
perfect! this is exactly what I was asking for.
