### ISSUE TITLE
Overzealous crop

### ISSUE THREAD

**Issue by kc9jud** [abarker/pdfCropMargins#47]
Given this file as input:
[Z03-N03-Z02-N04-survey_EXTRACT.pdf](https://github.com/abarker/pdfCropMargins/files/10740608/Z03-N03-Z02-N04-survey_EXTRACT.pdf)
I get this with `-s`
[Z03-N03-Z02-N04-survey-crop_EXTRACT.pdf](https://github.com/abarker/pdfCropMargins/files/10740607/Z03-N03-Z02-N04-survey-crop_EXTRACT.pdf)
Note that the number on the left axis (3.5) is cut off. This does not happen if I use, e.g., [`pdfcrop`](https://pdfcrop.sourceforge.net/):
[Z03-N03-Z02-N04-survey_EXTRACT-crop.pdf](https://github.com/abarker/pdfCropMargins/files/10740647/Z03-N03-Z02-N04-survey_EXTRACT-crop.pdf)

Any ideas what's going wrong? These are PDFs created by matplotlib...

**Comment by kc9jud** [comment]
Using `-cp` seems to produce the same output as `pdfcrop`, but I'm a bit surprised that `-cgr` does not, since I thought `pdfcrop` used Ghostscript internally.

**Comment by abarker** [comment]
This looks like a fairly normal issue with the bounding-box finding methods.  You might try changing the threshold value (`-t`) to see what effect that has, since the internal bounding-box detecting method (using Pillow on rendered images) probably uses a different threshold than Ghostscript.

The `-c gr` option still uses the Pillow bounding-box detection on Ghostscript-generated renderings.  The `-c gb` option uses the actual Ghostscript-detected boxes, and would probably be closer to pdfcrop.

Another thing to try is to increase the resolution of the renderings using `-x` and `-y`, which will be slower but more accurate.

You can also add a point or two to the margins by using the `-a` option with a negative value (or the `-a4` option to do each margin separately).

**Comment by kc9jud** [comment]
@abarker Changing the threshold was indeed necessary and sufficient. I found that a threshold of 224 (0xE0) or lower caused the cut-off text, while any threshold of 225 or higher gave a reasonable bounding box. That threshold seems to be independent of the resolution, so I guess it must have something to do with the way the number is rendered in that particular font. It certainly seems like more than a coincidence that the threshold needed to be above 0b11100000...
