### ISSUE TITLE
Plans to preserve pdf annotations?

### ISSUE THREAD

**Issue by costis-t** [abarker/pdfCropMargins#6]
Hello, 

Thanks for the amazing pdfCropMargins! 

Do you have any plans to crop PDF files while preserving pdf annotations like clickable links from the table of contents to specific pages of the PDF document? 
I think this information is stored in a pdf file in a different way than the text content of the pdf file making such a feature quite challenging. If you have tried implementing something like this, do you think it's easy, demanding, difficult, or impossible to do? (!)

**Comment by abarker** [comment]
By table of contents do you mean the outline which appears in readers like Acrobat Reader, to the left of the actual document?  The current version of the program should already preserve clickable links from the outline to places in the document.  This was added with the enhancement of Issue #2, in April.  Those are stored in the document catalog, which the program tries to copy over if it can.

If you mean links in the actual table of contents which is part of the paper, they should also work.

The fit of a page on the screen may change due to a link, but that would be difficult to modify.  (If it happens in Acrobat Reader I usually use Ctrl-0 to fix it back to how I prefer it.)  As usual, if the PDF has errors in it then links may not work.
